- name: Swap file
  raw: "mkswap {{item.device}}{{item.number}}"
  when: "'swap' in item.flags"

- name: System file
  filesystem:
    force: yes
    fstype: "{{item.fstype}}"
    dev: "{{item.device}}{{item.number}}"
    opts: "{{item.opts | default()}}"
  when: "'lvm' in item.flags or 'boot' in item.flags"