---
# tasks file for roles/arch_install
# only gpt for now

- name: create partition
  include_tasks: partition.yml

- name: install arch
  shell: "pacstrap /mnt linux base base-devel efibootmgr grub networkmanager"

- name: start swap
  shell: "swapon {{item.device}}{{item.number}}"
  when: "'swap' in item.flags"
  loop: "{{ partition }}"
  loop_control:
    extended: yes

- name: Generate fstab
  shell: "genfstab -U -p /mnt >> /mnt/etc/fstab"

#- name: Reboot
#  reboot:
#    connect_timeout: 1
#    reboot_timeout: 1