---
# tasks file for roles/arch_install
# only gpt for now

- name: create partition
  include_tasks: partition.yml

- name: install arch
  raw: "pacstrap {{mount_point}} linux base base-devel efibootmgr grub networkmanager"

- name: start swap
  raw: "swapon {{item.device}}{{item.number}}"
  when: "'swap' in item.flags"
  loop: "{{ partition }}"
  loop_control:
    extended: yes

- name: Generate fstab
  raw: "genfstab -U -p {{mount_point}} >> {{mount_point}}/etc/fstab"

#- name: Reboot
#  reboot:
#    connect_timeout: 1
#    reboot_timeout: 1