- name: install parted
  pacman:
    name: parted
    state: present

- name: Create partition
  parted:
    device: "{{item.device}}"
    label: "{{item.label}}"
    number: "{{item.number}}"
    part_start: "{{item.part_start}}"
    part_end: "{{ item.part_end }}"
    flags: "{{ item.flags }}"
    state: present
  loop: "{{ partition }}"
  loop_control:
    extended: yes

- name: Format partition
  include_tasks: format_partition.yml
  loop: "{{ partition }}"
  loop_control:
    extended: yes

- name: Mount partition
  include_tasks: mount.yml
  loop: "{{ partition }}"
  loop_control:
    extended: yes
