---
# ansible config host
ansible_connection: chroot
ansible_host: /mnt
ansible_chroot_exe: /usr/bin/arch-chroot
ansible_executable: /bin/bash


time_zone: Europe/Bucharest
hostname: arch
password: asd

user_name: dragos
user_password: asd