---
- name: install arch linux
  hosts: local
  roles:
    - arch_install

- name: config arch linux
  hosts: arch_chroot
  gather_facts: false
  roles:
    - ramdisk_environmen
    - grub
    - network
    - language
    - localtime
#    - root_password
#    - util_package_install
#    - yay
#    - samba
  post_tasks:
    - name: reboot after install
      raw: "reboot"
