---
- name: install arch linux
  hosts: local

  vars:
    partition:
      - device: /dev/sda
        label: gpt
        part_start: 0%
        part_end: 512MiB
        flags: [boot, esp]
        fstype: vfat
        opts: -F32
        mnt_path: /boot/efi

      - device: /dev/sda
        label: gpt
        part_start: 512MiB
        part_end: 1GiB
        flags: [swap]

      - device: /dev/sda
        label: gpt
        part_start: 1GiB
        part_end: 100%
        flags: [lvm]
        fstype: ext4
        mnt_path: /mnt
        install_linux: true

  tasks:
    - debug:
        msg: "{{ item }}"
      when: "item.install_linux is defined and item.install_linux == true"
      loop: "{{ partition }}"
      loop_control:
        extended: yes