---
- name: install arch linux
  hosts: local

  vars:
    mount_point: /mnt
    partition:
      - device: /dev/sda
        number: 1
        label: gpt
        part_start: 0%
        part_end: 512MiB
        flags: [boot, esp]
        fstype: vfat
        opts: -F32
        mnt_path: /boot/efi

      - device: /dev/sda
        number: 2
        label: gpt
        part_start: 512MiB
        part_end: 1GiB
        flags: [swap]

      - device: /dev/sda
        number: 3
        label: gpt
        part_start: 1GiB
        part_end: 100%
        flags: [lvm]
        fstype: ext4
        mnt_path: "{{mount_point}}"

    boot_partition: "{{ partition[0] }}"
    hostname: arch

  tasks:
    - debug:
        msg: "{{ boot_partition }}"
      when: "boot_partition.label == 'gpt'"

    - name: modify locale.gen
      lineinfile:
        dest: locale.gen
        line: |
          en_US.UTF-8 UTF-8
          en_US ISO-8859-1
        create: yes