---
# tasks file for roles/language

- name: modify locale.gen
  lineinfile:
    dest: /etc/locale.gen
    line: |
      en_US.UTF-8 UTF-8
      en_US ISO-8859-1
    create: yes

- name: modify locale.conf
  lineinfile:
    dest: /etc/locale.conf
    line: |
      LANG=en_US.UTF-8
    create: yes

- name: generate locale
  raw: "locale-gen"