---
# tasks file for add_user

- name: check user
  raw: echo {{user}}
  register: output

- debug:
    msg: "{{output.stdout}}"

- name: install sudo
  pacman:
    name: sudo
    state: present

- name: echo user
  user:
    name: "{{user_name}}"
    password: "{{ user_password | password_hash('sha512') }}"
    groups:
      - wheel
    state: present
    system: yes
    shell: /bin/bash
    createhome: yes
    home: /home/{{user}}

- name: Allow specified groups to sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '# %wheel.*NOPASSWD'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'